### ISSUE TITLE
Add comments for strangers

### ISSUE THREAD

**Issue by SuperKaninchen** [tttiago/ChessBroadcaster#2]
Hi there,
just a GitHub stranger who set up your project on a machine and successfully ran it.
Right now, I don't really understand what exactly your code does / what variables mean, so I'd extremely grateful if you could comment some more lines of your code. A simple reference like "this variable contains that, see library documentation" would suffice as you use many libraries most python developers aren't familiar with.
Many thanks!

PS: I've forked this repo and my fork currently has one [open issue](https://github.com/SuperKaninchen/ChessBroadcaster/issues/2) which describes one of the problems I had while setting all of this up, and I would love your input considering it, since you know best what your code is supposed to do

**Comment by tttiago** [comment]
Hey! 
I'm glad you managed to set it up. I agree that the software is not quite at the stage where anyone can swiftly set it up and have it work.
Can you specify which files you would like to see more comments on? If you have any specific doubt, I am also happy to help.

Note also that I have build my solution on top of https://github.com/karayaman/Play-online-chess-with-real-chess-board and I have treated many of the move recognition code as a black box. I have mostly focused on the interaction with the cameras and lichess.

Regards,
Tiago
